title: AlphaOmega Site
description: Working site info
theme: just-the-docs

url: https://CheetahChrome.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
