title: AlphaOmega Site
description: Working site info
theme: just-the-docs

logo: "/assets/images/MomDad45_2.jpg"

domain: CheetahChrome.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
baseurl: /AlphaOmega      # place folder name if the site is served in a subfolder

url: https://CheetahChrome.github.io
enable_copy_code_button: true

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

mermaid:
  version "9.3.0"

callouts:
# the colors grey-lt, grey-dk, purple, blue, green, yellow, and red are predefined;
  warning:
    title: Warning
    color: red  

# Footer content
#footer_content: "Copyright &copy; 2023 William Wegerson. Distributed by an <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a>"
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/CheetahChrome/AlphaOmega" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

collections_dir: documents

# Comment out this section if pushing to github.
# Uncomment for local. (divided by 0 included in default.html)
# exclude: 
#   - git/

# Define Jekyll collections
collections:
  Angular:
    permalink: "/:collection/:path/"
    output: true  
  Architecture:
    permalink: "/:collection/:path/"
    output: true            
  Git:
    permalink: "/:collection/:path/"
    output: true
  NetCore:
    permalink: "/:collection/:path/"
    output: true 
  Node:
    permalink: "/:collection/:path/"
    output: true       
  Tech:
    permalink: "/:collection/:path/"
    output: true       
just_the_docs:
  collections:
    Angular:
      name: Angular
    Architecture:
      name: Architecture      
    Git:
      name: Git
    NetCore:
      name: Net Core
    Node:
      name: Node.Js  
    NoSQL:
      name: No SQL    
    Tech:
      name: Tech       
    